apiVersion: v1
kind: Service
metadata:
  name: powerdnsadmin
  namespace: powerdnsadmin
  labels:
    app: powerdnsadmin
spec:
  ports:
  - name: http
    port: 39800
    targetPort: 39800
  selector:
    app: powerdnsadmin

